version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: talachapp
    volumes:
      - ./postgres:/var/lib/postgresql/data
